server:
  port: 8989

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_manage?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 6000

mybatis:
  #  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:generator/*.xml
